### ISSUE TITLE
Problem opening input.bcf -- No debug log

### ISSUE THREAD

**Issue by George3d6** [Illumina/akt#30]
I converted a vcf to bcf and tried running your tool with the following command:
`./akt pca -W data/wgs.grch37.vcf.gz input.bcf`
The only logs I get are:

```
Input: input.bcf
Using file data/wgs.grch37.vcf.gz for PCA weights
Problem opening input.bcf
```

Is see no debug option to make this message more verbose and figure out what the issue is, does a flag for verbose output exist ?

I don't believe the problem is permission related, here's the `stats` output for `input.bcf`:

```
  File: input.bcf
  Size: 557747163       Blocks: 1089360    IO Block: 4096   regular file
Device: fd01h/64769d    Inode: 10640983    Links: 1
Access: (0664/-rw-rw-r--)  Uid: ( 1000/  george)   Gid: ( 1000/  george)
Access: 2020-02-10 15:23:13.371180294 +0200
Modify: 2020-02-10 15:22:44.071013086 +0200
Change: 2020-02-10 15:22:44.071013086 +0200
 Birth: 
```
